Apollo Client v4 #11733 (#234)
* Apollo Client v4 #11733

Going forward the main differences in usage are:

```diff
 apollo
     .query({query: myQuery})
     .pipe(
+        ignoreErrors(),
         map(result => result.data.myQuery),
     );
```

```diff
 apollo
     .watchQuery({
         query: myQuery,
+        notifyOnNetworkStatusChange: false,
     })
     .valueChanges
     .pipe(
+        onlyCompleteData(),
         map(result => result.data.myQuery),
     );
```

Alos, Natural has a new `createErrorLink()`, with related
tests moved from Epicerio. To make it reasonnable a feature-complete
`ErrorService` now also lives in Natural, instead of in each projects
with very minor differences.

* Enable consistent type imports/exports #11733

In hope to speed up transpilation and have better tree shaking and/or
chunking

* Restore 502 error handling #11733

* Restore waiting on Apollo queries #11733

* Meaningful variable name #11733

* BREAKING: `modelService.delete()` does not `refetchObservableQueries()` #12584

The most common use case for `modelService.delete()` is from a page
detail, and after deletion the user is redirected to the page listing.
So there is no need to `refetchObservableQueries()` unconditionally.

# Other use cases

For other use cases we can reload specific queries like those
examples.

## Dialog

From a dialog on top of the listing page:

```ts
this.itemService
    .delete([id], {
        // Wait till we refresh the list under the dialog before closing the dialog, to avoid re-clicking on the just deleted item
        refetchQueries: [itemsQuery],
        awaitRefetchQueries: true,
    })
    .subscribe({
        next: () => {
            this.alertService.info(`Supprimé`);
            this.dialogRef.close();
        }
    });
```

## Inline deletion in listing

From a listing page where deletion is directly accessible on the row:

```ts
this.itemService.delete([id], {
    refetchQueries: [itemsQuery],
}).subscribe({
    next: () => {
        this.alertService.info(`Supprimé`);
    },
    error: () => this.deleting.delete(id),
});
```

## Bulk deleting

Bulk deleting via `NaturalAbstractList.bulkDelete()` still automatically
refetch the listing of items, but no other queries anymore.

* BREAKING: `modelService.create()` does not `refetchObservableQueries()` #12584

The most common use case for `modelService.create()` is from a page
detail for creation, and after the creation the user is redirected
to the page detail for edition. So there is no need to
`refetchObservableQueries()` unconditionally.

# Other use cases

For other use cases we can reload specific queries like those
examples.

## Dialog

From a dialog on top of the listing page:

```ts
this.itemService
    .create({...}, {
        // Refresh the list under the dialog
        refetchQueries: [itemsQuery]
    })
    .subscribe(newItem => {
        this.alertService.info('Créé');
        this.dialogRef.close(newItem);
});
```

## Inline creation in listing

From a listing page where row creation is inline, there is nothing to do,
because the row already exists before we even mutate the server.

* BREAKING: modelService `update()`, `updateNow()` and `createOrUpdate()` do not `refetchObservableQueries()` #12584

The most common use case for `modelService.updateNow()`, and variants,
is from a page detail for edition. The update mutation itself already
fetches the very few fields that are server computed and should
be refetched. So there is no need to `refetchObservableQueries()`
unconditionally.

# Other use cases

For other use cases we can reload specific queries like those
examples.

## Dialog

From a dialog on top of the listing page:

```ts
this.itemService
    .updateNow({...}, {
        // Wait till we refresh the list under the dialog before closing the dialog, to avoid re-clicking on the just updated item
        refetchQueries: [itemsQuery],
        awaitRefetchQueries: true
    })
    .subscribe(newItem => {
        this.alertService.info('Mis à jour');
        this.dialogRef.close(newItem);
});
```

## Inline update in listing

From a listing page where row update is inline, there is nothing to do,
because the row already is up to date before we even mutate the server.

## Bulk updating

Bulk updating is extremely rare in our projects, and should be treated
on a case by base basis.

* BREAKING: modelService `update()`, `updateNow()` and `createOrUpdate()` do not `refetchObservableQueries()` #12584

The most common use case for `modelService.updateNow()`, and variants,
is from a page detail for edition. The update mutation itself already
fetches the very few fields that are server computed and should
be refetched. So there is no need to `refetchObservableQueries()`
unconditionally.

# Other use cases

For other use cases we can reload specific queries like those
examples.

## Dialog

From a dialog on top of the listing page:

```ts
this.itemService
    .updateNow({...}, {
        // Wait till we refresh the list under the dialog before closing the dialog, to avoid re-clicking on the just updated item
        refetchQueries: [itemsQuery],
        awaitRefetchQueries: true
    })
    .subscribe(newItem => {
        this.alertService.info('Mis à jour');
        this.dialogRef.close(newItem);
});
```

## Inline update in listing

From a listing page where row update is inline, there is nothing to do,
because the row already is up to date before we even mutate the server.

## Bulk updating

Bulk updating is extremely rare in our projects, and should be treated
on a case by base basis.
Drop unused `BookingWithOwnerService.terminateBooking()` #12584
Drop debug code #12584

* Resolved model can be refetched #12584

Resolved model on a detail page is an active query in Apollo, so it
can be refetched like most other queries.

* Closing a panel will refresh the data of the panel under it #12244

So the panel that is newly visible will again receive `initPanel()` and
`ngOnInit`, like a native Angular routing would do.

* Minor comment update